kumuluzee:
  name: rso-slike
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  env:
    name: dev
  datasources:
  - jndi-name: jdbc/slike
    connection-url: jdbc:postgresql://sl-eu-gb-p02.dblayer.com:16079/compose
#    connection-url: jdbc:postgresql://192.168.99.100:5433/slika
#      connection-url: jdbc:postgresql://192.168.99.100:5433/slika
#    username: postgres
#    password: postgres
    username: admin
    #username: postgres
    password: MVAFTGCOCZMSODPN
    max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="customers">
                          <Appenders>
                              <Console name="console" target="SYSTEM_OUT">
                                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                              </Console>
                              <Socket name="logstash" host="70fb464a-c9f2-405c-a495-9b9793e6ee29-ls.logit.io"
                              port="13249" protocol="tcp">
                                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                              </Socket>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                              <Root level="all">
                                  <AppenderRef ref="console" level="info"/>
                                  <AppenderRef ref="logstash" level="trace"/>
                              </Root>
                          </Loggers>
                      </Configuration>'