kumuluzee:
  name: rso-slike
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
  - jndi-name: jdbc/slike
#    connection-url: jdbc:postgresql://sl-eu-gb-p02.dblayer.com:16079/compose
    connection-url: jdbc:postgresql://192.168.99.100:5432/postgres
#      connection-url: jdbc:postgresql://192.168.99.100:5433/slika
    username: postgres
    password: postgres
#    username: admin
#    password: MVAFTGCOCZMSODPN
    max-pool-size: 20
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15
# metrics:
        ##    web-instrumentation:
      ##      - name: album-endpoint
      ##        url-pattern: /v1/album/*
  app-properties:
    external-services:
      enabled: true
    healthy: true
