apiVersion: apps/v1
kind: Deployment
metadata:
  name: slike-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slike
  template:
    metadata:
      labels:
        app: slike
    spec:
      containers:
      - image: bostjan15/rsoslike
        name: slike
        env:
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: gcloud
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://sl-eu-gb-p02.dblayer.com:16079/compose
        - name: KUMULUZEE_DATASOURCES0_USERNAME
          value: admin
        - name: KUMULUZEE_DATASOURCES0_PASSWORD
          value: MVAFTGCOCZMSODPN
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        - containerPort: 8443
          name: grpc-server
          protocol: TCP
#        livenessProbe:
#          httpGet:
#            path: /health
#            port: server
#          initialDelaySeconds: 20
#          periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: slike
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: server
  selector:
    app: slike
