apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-11-27T06:35:04Z
  generation: 3
  labels:
    app: rsoslike
  name: rsoslike
  namespace: default
  resourceVersion: "61571"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/rsoslike
  uid: 931aa853-f20e-11e8-b362-42010a8000a1
spec:
  minReadySeconds: 1
  replicas: 1
  selector:
    matchLabels:
      app: rsoslike
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rsoslike
    spec:
      containers:
      - image: bostjan15/rsoslike:latest
        imagePullPolicy: Always
        name: rsoslike
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-11-27T06:35:15Z
    lastUpdateTime: 2018-11-27T06:35:15Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
